### ISSUE TITLE
Peer to Peer Review

### ISSUE THREAD

**Issue by LuisDavidRodriguez** [angeluray/awesome-books#4]
Kindly create a new variable here instead of write over an over again ``` monthAndDay.substring(4, 6); ```
you can just create a new ``` const stringToCheck = monthAndDay.substring(4, 6); ```
and then use that string into the if statement, because you are repeating ``` monthAndDay.substring(4, 6);  ``` 10 times 😄 
![image](https://user-images.githubusercontent.com/105079888/182874573-17534063-7c2d-4d0c-a1ab-2f28cc35912d.png)

**Comment by angeluray** [comment]
## Hi Luis,
![Patricio greeting](https://media.giphy.com/media/3ogwFGEHrVxusDbDjO/giphy.gif)

Thank you for your suggestions, we already applied those changes.
